# Generated by Django 2.1.7 on 2019-03-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TagDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.Image')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreadName', models.CharField(max_length=200)),
                ('TagId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='taggedimage',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ImageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.Image'),
        ),
        migrations.AddField(
            model_name='comment',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Practica.User'),
        ),
    ]
